### PR TITLE
Show horizontal scroll button for window tabs

### PR DESCRIPTION
**Pull request by okaryo**
like this
Screenshot 2023-10-15 at 10 37 51
Screenshot 2023-10-15 at 10 38 09

### CODE REVIEW

**Comment by Migotes** [comment]
Thank you for continuing to develop TabTabTab with so much energy and dedication!

**Comment by okaryo** [comment]
@Migotes 
Thank you. I've been little busy until mid-November, so I haven't had much time to dedicate to TabTabTab development. I apologize for that.

**Comment by Migotes** [comment]
Everything Ok as it is :)

I would be very happy if you would adjust the description on the Chrome website of TabTabTab (https://chrome.google.com/webstore/detail/tabtabtab-tab-manager/hfmnidllojimehmfjkclnadpebibhgoi) the same way as on your github page. I think not everyone looks at the github page to find out about TabTabTab's great group features ;)

I would also be very happy to see increasing user numbers for you. In Germany sometimes browser add-ons are presented on important computer internet sites - do you have that too? It would be great if TabTabTab becomes even better known. I would so wish that for you!

**Comment by okaryo** [comment]
@Migotes 
Unfortunately, the store's description format doesn't support rich elements like headings and images, similar to GitHub. 

I can track installation and user numbers through the store's dashboard, and I plan to regularly share these statistics on GitHub Discussions at #203 .
I'm delighted that you're interested in improving TabTabTab, and if you have any more suggestions or ideas for enhancements, please feel free to let me know!

**Pull request merged**
